### ISSUE TITLE
Question: null-loader vs. ignore-loader

### ISSUE THREAD

**Issue by t47io** [webpack-contrib/null-loader#11]
Does this loader essentially do the same as https://github.com/cherrry/ignore-loader? I wonder if they are interchangeable without problems. Thanks!

Since the `null-loader` is from `webpack-contrib`, is it recommended over `ignore-loader`?

**Comment by michael-ciniawsky** [comment]
@t47io Yes, the only difference is that `null-loader` adds a comment for the 'empty module'
