### ISSUE TITLE
Null-loader takes too much of the build time (possibly not a bug though)

### ISSUE THREAD

**Issue by grumd** [webpack-contrib/null-loader#36]
I've been very surprised to see this build time:

![](https://puu.sh/GCxqr/45f28ff7f2.png)

Config:
```
{
  test: /\.(sa|sc|c)ss$/,
  use: 'null-loader',
}
```

null-loader took 17 seconds for 1000 modules. Considering this loader is supposed to do nothing, this is pretty weird. ignore-loader took ~15-16 seconds which is pretty high as well, that's why I'm thinking this might be a webpack issue, not null-loader issue.

However, babel-loader with thread-loader took way less time, 25 seconds for 5400 modules. I was thinking null-loader is supposed to be faster than that, so faster than 4 seconds per 1000 modules.

Is it possible to speed up null-loader somehow?

- Operating System: W10
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.32.2
- null-loader Version: 4.0.1, latest

**Comment by alexander-akait** [comment]
Sorry, null-loader will be deprecated for wepback@5 due built-in ability to ignore using `alias.resolve`, so nothing to do here

**Comment by grumd** [comment]
Oh I see, thank you. I'll look into webpack 5.

**Comment by grumd** [comment]
@evilebottnawi Would be nice if you added this little bit of info into README.md though!

**Comment by alexander-akait** [comment]
@grumd Yep, I will do it
